"""
app.py

Streamlit MVP interface for the retinal disease screening capstone project.
A health worker uploads a retinal fundus image and receives a preliminary
diabetic retinopathy screening result, generated by the MobileNetV2 model
trained in model_notebook.ipynb.

Run locally:
    pip install streamlit tensorflow pillow numpy
    streamlit run app.py
"""

import numpy as np
import streamlit as st
from PIL import Image
import tensorflow as tf

MODEL_PATH = "dr_screening_model.h5"
IMG_SIZE = (224, 224)

st.set_page_config(
    page_title="Retinal Screening Assistant",
    page_icon="\U0001F441",
    layout="centered",
)

CUSTOM_CSS = """
<style>
@import url('https://fonts.googleapis.com/css2?family=Source+Sans+3:wght@400;600;700&family=Fraunces:wght@500;600&display=swap');

html, body, [class*="css"] {
    font-family: 'Source Sans 3', sans-serif;
}

.stApp {
    background-color: #F6F5F1;
}

.hero-title {
    font-family: 'Fraunces', serif;
    font-size: 2.1rem;
    font-weight: 600;
    color: #133C36;
    margin-bottom: 0.1rem;
}

.hero-sub {
    color: #4A5A57;
    font-size: 1.02rem;
    margin-bottom: 1.6rem;
}

.result-card {
    border-radius: 10px;
    padding: 1.4rem 1.6rem;
    margin-top: 1.2rem;
    border: 1px solid rgba(0,0,0,0.08);
}

.result-clear {
    background-color: #EAF3EE;
    border-left: 5px solid #2E7D5B;
}

.result-flagged {
    background-color: #FBF0E4;
    border-left: 5px solid #C97A2B;
}

.result-label {
    font-family: 'Fraunces', serif;
    font-size: 1.4rem;
    font-weight: 600;
    margin-bottom: 0.2rem;
}

.confidence-row {
    font-size: 0.95rem;
    color: #4A5A57;
}

.scope-note {
    font-size: 0.85rem;
    color: #6B7876;
    border-top: 1px solid rgba(0,0,0,0.08);
    margin-top: 2.2rem;
    padding-top: 0.9rem;
}
</style>
"""
st.markdown(CUSTOM_CSS, unsafe_allow_html=True)


@st.cache_resource
def load_model():
    try:
        return tf.keras.models.load_model(MODEL_PATH)
    except Exception:
        return None


def preprocess(image: Image.Image) -> np.ndarray:
    image = image.convert("RGB").resize(IMG_SIZE)
    arr = np.array(image).astype("float32")
    arr = tf.keras.applications.mobilenet_v2.preprocess_input(arr)
    return np.expand_dims(arr, axis=0)


st.markdown('<div class="hero-title">Retinal Screening Assistant</div>', unsafe_allow_html=True)
st.markdown(
    '<div class="hero-sub">Upload a retinal fundus image to get a preliminary '
    "diabetic retinopathy screening result.</div>",
    unsafe_allow_html=True,
)

model = load_model()

if model is None:
    st.warning(
        f"No trained model found at `{MODEL_PATH}`. Run `model_notebook.ipynb` first "
        "and place the saved `dr_screening_model.h5` file in this same folder."
    )

uploaded_file = st.file_uploader(
    "Retinal image (JPG or PNG)", type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:
    col1, col2 = st.columns([1, 1])

    image = Image.open(uploaded_file)
    with col1:
        st.image(image, caption="Uploaded image", use_container_width=True)

    with col2:
        if model is not None:
            with st.spinner("Analyzing image..."):
                x = preprocess(image)
                prob = float(model.predict(x, verbose=0)[0][0])

            dr_detected = prob > 0.5
            confidence = prob if dr_detected else (1 - prob)

            if dr_detected:
                st.markdown(
                    f"""
                    <div class="result-card result-flagged">
                        <div class="result-label">Signs of DR detected</div>
                        <div class="confidence-row">Model confidence: {confidence:.0%}</div>
                        <div class="confidence-row" style="margin-top:0.5rem;">
                            Recommended action: refer for specialist review.
                        </div>
                    </div>
                    """,
                    unsafe_allow_html=True,
                )
            else:
                st.markdown(
                    f"""
                    <div class="result-card result-clear">
                        <div class="result-label">No signs of DR detected</div>
                        <div class="confidence-row">Model confidence: {confidence:.0%}</div>
                        <div class="confidence-row" style="margin-top:0.5rem;">
                            Recommended action: routine follow-up screening.
                        </div>
                    </div>
                    """,
                    unsafe_allow_html=True,
                )
        else:
            st.info("Model not loaded — showing the interface only.")

st.markdown(
    '<div class="scope-note">This is an initial MVP screening for diabetic retinopathy '
    "only. Glaucoma and cataract screening, offline-first sync, and specialist referral "
    "routing are planned for the Final Capstone Implementation. This tool provides "
    "preliminary screening support and does not replace clinical diagnosis.</div>",
    unsafe_allow_html=True,
)
